channels:
- conda-forge
dependencies:
- python=3.8.8
- pip<=22.1.2
- pip:
  - mlflow
  - mypy-extensions==0.4.3
  - pandas==1.4.2
  - psutil==5.9.1
  - scikit-learn==1.1.1
  - typing-extensions==4.2.0
  - xgboost==1.6.1
name: mlflow-env
